# Generated by Django 6.0.3 on 2026-03-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
